### PR TITLE
Cleanup empty directories

### PR DESCRIPTION
**Pull request by scott-rc**
Thanks to @MillanWangGadget, I think I finally figured this out!

### CODE REVIEW

**Comment by MillanWangGadget** [comment]
One case of interest is when you have file `a/b/c.txt` and you delete folder `a/` in the editor
In that case, there is no empty folder file create when `a/b/c.txt` is deleted which will leave behind `a/b/`

I wonder if in that case, the Gadget editor should also make `a/` as an empty folder for a brief moment and then immediately delete it so that GGT gets the signal to delete `a/` and it's leftover children

**Comment by scott-rc** [comment]
> One case of interest is when you have file `a/b/c.txt` and you delete folder `a/` in the editor In that case, there is no empty folder file create when `a/b/c.txt` is deleted which will leave behind `a/b/`
> 
> I wonder if in that case, the Gadget editor should also make `a/` as an empty folder for a brief moment and then immediately delete it so that GGT gets the signal to delete `a/` and it's leftover children

I still need to add a test for this, but this commit should fix that scenario: [`65079da` (#1313)](https://github.com/gadget-inc/ggt/pull/1313/commits/65079daea99fee3b62e3728a6a6c54adf28cee85)

**Comment by scott-rc** [comment]
Added the test and changed how we track local file changes so we track them accurately.

**Review by MillanWangGadget — COMMENTED** [review]
RETROACTIVE REVIEW 
- 🍏 Deleting folders at the root of the project does not leave any leftover folders
- 🍏 Deleting folders in the middle of a nest for a nested folder leaves behind the expected folders in the local filesystem
- 🍏 Renaming a folder in the middle of a nested file path does not leave behind any unexpected folders in the local file system

This is awesome, thank you for this 👍

**Pull request merged**
